<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions name="NumberService" targetNamespace="http://tempuri.org/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:wsap="http://schemas.xmlsoap.org/ws/2004/08/addressing/policy" xmlns:wsa10="http://www.w3.org/2005/08/addressing" xmlns:tns="http://tempuri.org/" xmlns:msc="http://schemas.microsoft.com/ws/2005/12/wsdl/contract" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:wsx="http://schemas.xmlsoap.org/ws/2004/09/mex" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata" xmlns:wsa="http://schemas.xmlsoap.org/ws/2004/08/addressing" xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:wsaw="http://www.w3.org/2006/05/addressing/wsdl" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <wsdl:types>
    <xs:schema elementFormDefault="qualified" targetNamespace="http://tempuri.org/" xmlns:xs="http://www.w3.org/2001/XMLSchema">
      <xs:import namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays"/>
      <xs:element name="Sum">
        <xs:complexType>
          <xs:sequence>
            <xs:element minOccurs="0" name="values" nillable="true" type="q1:ArrayOfint" xmlns:q1="http://schemas.microsoft.com/2003/10/Serialization/Arrays"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="SumResponse">
        <xs:complexType>
          <xs:sequence>
            <xs:element minOccurs="0" name="SumResult" type="xs:int"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="Product">
        <xs:complexType>
          <xs:sequence>
            <xs:element minOccurs="0" name="values" nillable="true" type="q2:ArrayOfint" xmlns:q2="http://schemas.microsoft.com/2003/10/Serialization/Arrays"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="ProductResponse">
        <xs:complexType>
          <xs:sequence>
            <xs:element minOccurs="0" name="ProductResult" type="xs:int"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="Abs">
        <xs:complexType>
          <xs:sequence>
            <xs:element minOccurs="0" name="value" nillable="true" type="xs:string"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="AbsResponse">
        <xs:complexType>
          <xs:sequence>
            <xs:element minOccurs="0" name="AbsResult" type="xs:int"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:schema>
    <xs:schema attributeFormDefault="qualified" elementFormDefault="qualified" targetNamespace="http://schemas.microsoft.com/2003/10/Serialization/" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://schemas.microsoft.com/2003/10/Serialization/">
      <xs:element name="anyType" nillable="true" type="xs:anyType"/>
      <xs:element name="anyURI" nillable="true" type="xs:anyURI"/>
      <xs:element name="base64Binary" nillable="true" type="xs:base64Binary"/>
      <xs:element name="boolean" nillable="true" type="xs:boolean"/>
      <xs:element name="byte" nillable="true" type="xs:byte"/>
      <xs:element name="dateTime" nillable="true" type="xs:dateTime"/>
      <xs:element name="decimal" nillable="true" type="xs:decimal"/>
      <xs:element name="double" nillable="true" type="xs:double"/>
      <xs:element name="float" nillable="true" type="xs:float"/>
      <xs:element name="int" nillable="true" type="xs:int"/>
      <xs:element name="long" nillable="true" type="xs:long"/>
      <xs:element name="QName" nillable="true" type="xs:QName"/>
      <xs:element name="short" nillable="true" type="xs:short"/>
      <xs:element name="string" nillable="true" type="xs:string"/>
      <xs:element name="unsignedByte" nillable="true" type="xs:unsignedByte"/>
      <xs:element name="unsignedInt" nillable="true" type="xs:unsignedInt"/>
      <xs:element name="unsignedLong" nillable="true" type="xs:unsignedLong"/>
      <xs:element name="unsignedShort" nillable="true" type="xs:unsignedShort"/>
      <xs:element name="char" nillable="true" type="tns:char"/>
      <xs:simpleType name="char">
        <xs:restriction base="xs:int"/>
      </xs:simpleType>
      <xs:element name="duration" nillable="true" type="tns:duration"/>
      <xs:simpleType name="duration">
        <xs:restriction base="xs:duration">
          <xs:pattern value="\-?P(\d*D)?(T(\d*H)?(\d*M)?(\d*(\.\d*)?S)?)?"/>
          <xs:minInclusive value="-P10675199DT2H48M5.4775808S"/>
          <xs:maxInclusive value="P10675199DT2H48M5.4775807S"/>
        </xs:restriction>
      </xs:simpleType>
      <xs:element name="guid" nillable="true" type="tns:guid"/>
      <xs:simpleType name="guid">
        <xs:restriction base="xs:string">
          <xs:pattern value="[\da-fA-F]{8}-[\da-fA-F]{4}-[\da-fA-F]{4}-[\da-fA-F]{4}-[\da-fA-F]{12}"/>
        </xs:restriction>
      </xs:simpleType>
      <xs:attribute name="FactoryType" type="xs:QName"/>
      <xs:attribute name="Id" type="xs:ID"/>
      <xs:attribute name="Ref" type="xs:IDREF"/>
    </xs:schema>
    <xs:schema elementFormDefault="qualified" targetNamespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://schemas.microsoft.com/2003/10/Serialization/Arrays">
      <xs:complexType name="ArrayOfint">
        <xs:sequence>
          <xs:element minOccurs="0" maxOccurs="unbounded" name="int" type="xs:int"/>
        </xs:sequence>
      </xs:complexType>
      <xs:element name="ArrayOfint" nillable="true" type="tns:ArrayOfint"/>
    </xs:schema>
  </wsdl:types>
  <wsdl:message name="INumberService_Sum_InputMessage">
    <wsdl:part name="parameters" element="tns:Sum"/>
  </wsdl:message>
  <wsdl:message name="INumberService_Sum_OutputMessage">
    <wsdl:part name="parameters" element="tns:SumResponse"/>
  </wsdl:message>
  <wsdl:message name="INumberService_Product_InputMessage">
    <wsdl:part name="parameters" element="tns:Product"/>
  </wsdl:message>
  <wsdl:message name="INumberService_Product_OutputMessage">
    <wsdl:part name="parameters" element="tns:ProductResponse"/>
  </wsdl:message>
  <wsdl:message name="INumberService_Abs_InputMessage">
    <wsdl:part name="parameters" element="tns:Abs"/>
  </wsdl:message>
  <wsdl:message name="INumberService_Abs_OutputMessage">
    <wsdl:part name="parameters" element="tns:AbsResponse"/>
  </wsdl:message>
  <wsdl:portType name="INumberService">
    <wsdl:operation name="Sum">
      <wsdl:input wsaw:Action="http://tempuri.org/INumberService/Sum" message="tns:INumberService_Sum_InputMessage"/>
      <wsdl:output wsaw:Action="http://tempuri.org/INumberService/SumResponse" message="tns:INumberService_Sum_OutputMessage"/>
    </wsdl:operation>
    <wsdl:operation name="Product">
      <wsdl:input wsaw:Action="http://tempuri.org/INumberService/Product" message="tns:INumberService_Product_InputMessage"/>
      <wsdl:output wsaw:Action="http://tempuri.org/INumberService/ProductResponse" message="tns:INumberService_Product_OutputMessage"/>
    </wsdl:operation>
    <wsdl:operation name="Abs">
      <wsdl:input wsaw:Action="http://tempuri.org/INumberService/Abs" message="tns:INumberService_Abs_InputMessage"/>
      <wsdl:output wsaw:Action="http://tempuri.org/INumberService/AbsResponse" message="tns:INumberService_Abs_OutputMessage"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="BasicHttpBinding_INumberService" type="tns:INumberService">
    <soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="Sum">
      <soap:operation soapAction="http://tempuri.org/INumberService/Sum" style="document"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="Product">
      <soap:operation soapAction="http://tempuri.org/INumberService/Product" style="document"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="Abs">
      <soap:operation soapAction="http://tempuri.org/INumberService/Abs" style="document"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="NumberService">
    <wsdl:port name="BasicHttpBinding_INumberService" binding="tns:BasicHttpBinding_INumberService">
      <soap:address location="http://localhost/process"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>